/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs444project.presentation;

import cs444project.service.*;
import cs444project.domain.*;
import javax.swing.JOptionPane;

/**
 *
 * @author icentsn
 */
public class MainUI extends javax.swing.JFrame {
    private Account account = null;
    
    private BookTableModel model = new BookTableModel();
    
    private int selectedRow = -1;
    
    public void setAccount(Account account) {
        this.account = account;
        model.setBooks(account.getBooks());
    }
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        
        booksTbl.setModel(model);
        
        booksTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = booksTbl.rowAtPoint(evt.getPoint());
                if (row >= 0){
                    selectedRow = row;
                    titleFld.setText(model.getValueAt(row,0).toString());
                    categoryFld.setText(model.getValueAt(row,1).toString());
                    editionFld.setText(model.getValueAt(row,2).toString());
                    ratingFld.setText(model.getValueAt(row,3).toString());
                
            }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homepage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        booksTbl = new javax.swing.JTable();
        createBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        checkoutBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        Category = new javax.swing.JLabel();
        Edition = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        titleFld = new javax.swing.JTextField();
        categoryFld = new javax.swing.JTextField();
        editionFld = new javax.swing.JTextField();
        ratingFld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homepage.setBorder(javax.swing.BorderFactory.createTitledBorder("Home Page"));

        booksTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title", "Category", "Edition", "Rating"
            }
        ));
        jScrollPane1.setViewportView(booksTbl);

        createBtn.setText("Create");
        createBtn.setMaximumSize(new java.awt.Dimension(85, 29));
        createBtn.setMinimumSize(new java.awt.Dimension(85, 29));
        createBtn.setPreferredSize(new java.awt.Dimension(85, 29));
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.setMaximumSize(new java.awt.Dimension(85, 29));
        editBtn.setMinimumSize(new java.awt.Dimension(85, 29));
        editBtn.setPreferredSize(new java.awt.Dimension(85, 29));

        deleteBtn.setText("Delete");
        deleteBtn.setMaximumSize(new java.awt.Dimension(85, 29));
        deleteBtn.setMinimumSize(new java.awt.Dimension(85, 29));
        deleteBtn.setPreferredSize(new java.awt.Dimension(85, 29));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        checkoutBtn.setText("Checkout");
        checkoutBtn.setMaximumSize(new java.awt.Dimension(85, 29));
        checkoutBtn.setMinimumSize(new java.awt.Dimension(85, 29));
        checkoutBtn.setPreferredSize(new java.awt.Dimension(85, 29));

        searchBtn.setText("Search");

        Title.setText("Title");

        Category.setText("Category");

        Edition.setText("Edition");

        jLabel1.setText("Rating");

        javax.swing.GroupLayout homepageLayout = new javax.swing.GroupLayout(homepage);
        homepage.setLayout(homepageLayout);
        homepageLayout.setHorizontalGroup(
            homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepageLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homepageLayout.createSequentialGroup()
                        .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homepageLayout.createSequentialGroup()
                                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Title)
                                    .addComponent(Category)
                                    .addComponent(Edition)
                                    .addComponent(jLabel1))
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homepageLayout.createSequentialGroup()
                                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleFld)
                            .addGroup(homepageLayout.createSequentialGroup()
                                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(homepageLayout.createSequentialGroup()
                                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(212, 212, 212)
                                        .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(categoryFld, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editionFld, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ratingFld, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        homepageLayout.setVerticalGroup(
            homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepageLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(titleFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Category)
                    .addComponent(categoryFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edition)
                    .addComponent(editionFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ratingFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(homepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(homepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        Book book = new Book();
        book.setTitle(titleFld.getText());
        book.setCategory(categoryFld.getText());
        book.setEdition(editionFld.getText());
        book.setRating(ratingFld.getText());
        
        boolean isValid = book.validate();
        if(!isValid) {
            JOptionPane.showMessageDialog(this, 
                    "All fields are required for a Book", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        account.add(book);
        IAccountSvc impl = AccountSvcCacheImpl.getInstance();
        account = impl.update(account);
        if(account == null){
            JOptionPane.showMessageDialog(this, 
                    "Your Book was not saved; please try again", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        model.fireTableDataChanged();
        
        JOptionPane.showMessageDialog(this, "Your new Book has been saved",
                "Save Book", JOptionPane.INFORMATION_MESSAGE);
        titleFld.setText("");
        categoryFld.setText("");
        editionFld.setText("");
        ratingFld.setText("");
    }//GEN-LAST:event_createBtnActionPerformed

    
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if(selectedRow >= 0) {
            Book book = account.getBooks().get(selectedRow);
            book.setTitle(titleFld.getText());
            book.setCategory(categoryFld.getText());
            book.setEdition(editionFld.getText());
            book.setRating(ratingFld.getText());
            model.fireTableDataChanged();
            reset();
        }
    }
    
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        if(selectedRow >= 0) {
            int selectedOption = JOptionPane.showConfirmDialog(null,
                    "Delete the selected row?",
                            "Yes/No",
                            JOptionPane.YES_NO_CANCEL_OPTION);
            if (selectedOption == JOptionPane.YES_OPTION){
                account.getBooks().remove(selectedRow);
                model.fireTableDataChanged();
                reset();
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void reset(){
        selectedRow = -1;
        titleFld.setText("");
        categoryFld.setText("");
        editionFld.setText("");
        ratingFld.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Category;
    private javax.swing.JLabel Edition;
    private javax.swing.JLabel Title;
    private javax.swing.JTable booksTbl;
    private javax.swing.JTextField categoryFld;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField editionFld;
    private javax.swing.JPanel homepage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ratingFld;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField titleFld;
    // End of variables declaration//GEN-END:variables
}
